package interfaces;

import principal.Main;
import banco.LetrasDAO;
import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import entidade.Letra;
import entidade.Som;
import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Panel;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

public class Inicial extends javax.swing.JFrame {

    private Random rd;
    private LetrasDAO letrasDAO;
    private Thread td;
    private Letra lSorteada;
    private Letra lSorteada1;
    private Letra lSorteada2;
    private Letra certa;
    private int score = 0;
    private int vida = 3;
    private CardLayout cl;

    public Inicial(int score) {
        getContentPane().setBackground(Color.WHITE);
        try {
            UIManager.setLookAndFeel(new WindowsLookAndFeel());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
            System.out.println("Problema no LookAndFeel");
        }
        setUndecorated(true);
        rd = new Random();
        letrasDAO = new LetrasDAO();
        td = new Thread();
        this.score = score;

        char alfa[] = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'};
        for (int i = 0; i < alfa.length; i++) {
            Som som = new Som("/audio/" + alfa[i] + ".wav");
            Letra l = new Letra(alfa[i], i + 1, som);
            letrasDAO.salvar(l);
        }

        int sorteado = rd.nextInt(26);
        lSorteada = letrasDAO.buscarId(sorteado);

        sorteado = rd.nextInt(26);
        lSorteada1 = letrasDAO.buscarId(sorteado);

        sorteado = rd.nextInt(26);
        lSorteada2 = letrasDAO.buscarId(sorteado);

        if (lSorteada == lSorteada1 || lSorteada == lSorteada2 || lSorteada1 == lSorteada2) {
            sortear();
        }
        if (lSorteada == null || lSorteada1 == null || lSorteada2 == null) {
            sortear();
        }

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        panelPrincipal = new javax.swing.JPanel();
        acerteLetra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        alfabeto = new javax.swing.JButton();
        lbAcer2 = new javax.swing.JLabel();
        lbAcertos1 = new javax.swing.JLabel();
        lbAcer3 = new javax.swing.JLabel();
        panelAlfabeto = new javax.swing.JPanel();
        letraB = new javax.swing.JToggleButton();
        letraA = new javax.swing.JToggleButton();
        letraC = new javax.swing.JToggleButton();
        letraD = new javax.swing.JToggleButton();
        letraE = new javax.swing.JToggleButton();
        letraF = new javax.swing.JToggleButton();
        letraG = new javax.swing.JToggleButton();
        letraL = new javax.swing.JToggleButton();
        letraM = new javax.swing.JToggleButton();
        letraI = new javax.swing.JToggleButton();
        letraN = new javax.swing.JToggleButton();
        letraH = new javax.swing.JToggleButton();
        letraJ = new javax.swing.JToggleButton();
        letraK = new javax.swing.JToggleButton();
        letraR = new javax.swing.JToggleButton();
        letraU = new javax.swing.JToggleButton();
        letraW = new javax.swing.JToggleButton();
        letraO = new javax.swing.JToggleButton();
        letraV = new javax.swing.JToggleButton();
        letraP = new javax.swing.JToggleButton();
        letraT = new javax.swing.JToggleButton();
        letraZ = new javax.swing.JToggleButton();
        letraY = new javax.swing.JToggleButton();
        letraX = new javax.swing.JToggleButton();
        letraQ = new javax.swing.JToggleButton();
        letraS = new javax.swing.JToggleButton();
        lbQual2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelJogar = new javax.swing.JPanel();
        lbChances = new javax.swing.JLabel();
        letra2 = new javax.swing.JToggleButton();
        letra1 = new javax.swing.JToggleButton();
        letra3 = new javax.swing.JToggleButton();
        lbQual1 = new javax.swing.JLabel();
        lbAcer1 = new javax.swing.JLabel();
        lbAcertos = new javax.swing.JLabel();
        lbChances1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lbAcer4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenu.setLayout(new java.awt.CardLayout());

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        acerteLetra.setBackground(new java.awt.Color(255, 51, 51));
        acerteLetra.setFont(new java.awt.Font("Bebas Neue Regular", 0, 24)); // NOI18N
        acerteLetra.setForeground(new java.awt.Color(255, 51, 51));
        acerteLetra.setText("ACERTE A LETRA!");
        acerteLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acerteLetraActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/titulo.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setMaximumSize(new java.awt.Dimension(1438, 393));

        alfabeto.setBackground(new java.awt.Color(0, 153, 153));
        alfabeto.setFont(new java.awt.Font("Bebas Neue Regular", 0, 24)); // NOI18N
        alfabeto.setForeground(new java.awt.Color(0, 153, 153));
        alfabeto.setText("VER TODAS AS LETRAS");
        alfabeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alfabetoActionPerformed(evt);
            }
        });

        lbAcer2.setFont(new java.awt.Font("Swis721 Blk BT", 0, 36)); // NOI18N
        lbAcer2.setForeground(new java.awt.Color(204, 51, 0));
        lbAcer2.setText("X");
        lbAcer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAcer2MouseClicked(evt);
            }
        });

        lbAcertos1.setFont(new java.awt.Font("Swis721 Blk BT", 0, 36)); // NOI18N
        lbAcertos1.setForeground(new java.awt.Color(98, 113, 111));
        lbAcertos1.setText(String.valueOf(score));

        lbAcer3.setFont(new java.awt.Font("Swis721 Blk BT", 0, 36)); // NOI18N
        lbAcer3.setForeground(new java.awt.Color(0, 153, 92));
        lbAcer3.setText("ACERTOS:");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(acerteLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbAcertos1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(lbAcer2)
                .addGap(39, 39, 39))
            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPrincipalLayout.createSequentialGroup()
                    .addGap(232, 232, 232)
                    .addComponent(lbAcer3)
                    .addContainerGap(353, Short.MAX_VALUE)))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lbAcer2)))
                .addGap(45, 45, 45)
                .addComponent(acerteLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(alfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(lbAcertos1)
                .addGap(23, 23, 23))
            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                    .addContainerGap(475, Short.MAX_VALUE)
                    .addComponent(lbAcer3)
                    .addGap(22, 22, 22)))
        );

        panelMenu.add(panelPrincipal, "principal");

        panelAlfabeto.setBackground(new java.awt.Color(255, 255, 255));

        letraB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/B.png"))); // NOI18N
        letraB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraBActionPerformed(evt);
            }
        });

        letraA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/A.png"))); // NOI18N
        letraA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraAActionPerformed(evt);
            }
        });

        letraC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/C.png"))); // NOI18N
        letraC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraCActionPerformed(evt);
            }
        });

        letraD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/D.png"))); // NOI18N
        letraD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraDActionPerformed(evt);
            }
        });

        letraE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/E.png"))); // NOI18N
        letraE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraEActionPerformed(evt);
            }
        });

        letraF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/F.png"))); // NOI18N
        letraF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraFActionPerformed(evt);
            }
        });

        letraG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/G.png"))); // NOI18N
        letraG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraGActionPerformed(evt);
            }
        });

        letraL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/L.png"))); // NOI18N
        letraL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraLActionPerformed(evt);
            }
        });

        letraM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/M.png"))); // NOI18N
        letraM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraMActionPerformed(evt);
            }
        });

        letraI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/I.png"))); // NOI18N
        letraI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraIActionPerformed(evt);
            }
        });

        letraN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/N.png"))); // NOI18N
        letraN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraNActionPerformed(evt);
            }
        });

        letraH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/H.png"))); // NOI18N
        letraH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraHActionPerformed(evt);
            }
        });

        letraJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/J.png"))); // NOI18N
        letraJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraJActionPerformed(evt);
            }
        });

        letraK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/K.png"))); // NOI18N
        letraK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraKActionPerformed(evt);
            }
        });

        letraR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/R.png"))); // NOI18N
        letraR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraRActionPerformed(evt);
            }
        });

        letraU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/U.png"))); // NOI18N
        letraU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraUActionPerformed(evt);
            }
        });

        letraW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/W.png"))); // NOI18N
        letraW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraWActionPerformed(evt);
            }
        });

        letraO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/O.png"))); // NOI18N
        letraO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraOActionPerformed(evt);
            }
        });

        letraV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/V.png"))); // NOI18N
        letraV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraVActionPerformed(evt);
            }
        });

        letraP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/P.png"))); // NOI18N
        letraP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraPActionPerformed(evt);
            }
        });

        letraT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/T.png"))); // NOI18N
        letraT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraTActionPerformed(evt);
            }
        });

        letraZ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Z.png"))); // NOI18N
        letraZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraZActionPerformed(evt);
            }
        });

        letraY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Y.png"))); // NOI18N
        letraY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraYActionPerformed(evt);
            }
        });

        letraX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/X.png"))); // NOI18N
        letraX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraXActionPerformed(evt);
            }
        });

        letraQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Q.png"))); // NOI18N
        letraQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraQActionPerformed(evt);
            }
        });

        letraS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/S.png"))); // NOI18N
        letraS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraSActionPerformed(evt);
            }
        });

        lbQual2.setFont(new java.awt.Font("Swis721 Blk BT", 0, 36)); // NOI18N
        lbQual2.setForeground(new java.awt.Color(98, 113, 111));
        lbQual2.setText("Este é o Alfabeto");

        jButton1.setFont(new java.awt.Font("Swis721 Blk BT", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(98, 113, 111));
        jButton1.setText("< Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAlfabetoLayout = new javax.swing.GroupLayout(panelAlfabeto);
        panelAlfabeto.setLayout(panelAlfabetoLayout);
        panelAlfabetoLayout.setHorizontalGroup(
            panelAlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlfabetoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelAlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAlfabetoLayout.createSequentialGroup()
                        .addGroup(panelAlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelAlfabetoLayout.createSequentialGroup()
                                .addComponent(letraH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(letraI)
                                .addGap(12, 12, 12)
                                .addComponent(letraJ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(letraK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(letraL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(letraM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(letraN))
                            .addGroup(panelAlfabetoLayout.createSequentialGroup()
                                .addComponent(letraA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(letraB)
                                .addGap(12, 12, 12)
                                .addComponent(letraC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(letraD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(letraE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(letraF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(letraG)))
                        .addContainerGap())
                    .addGroup(panelAlfabetoLayout.createSequentialGroup()
                        .addGroup(panelAlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlfabetoLayout.createSequentialGroup()
                                .addComponent(letraV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(letraW)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(letraX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlfabetoLayout.createSequentialGroup()
                                .addComponent(letraO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(letraP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(letraQ)
                                .addGap(12, 12, 12)))
                        .addGroup(panelAlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAlfabetoLayout.createSequentialGroup()
                                .addComponent(letraR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(letraS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(letraT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(letraU)
                                .addGap(27, 27, 27))
                            .addGroup(panelAlfabetoLayout.createSequentialGroup()
                                .addComponent(letraY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(letraZ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlfabetoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbQual2)
                .addGap(218, 218, 218))
        );
        panelAlfabetoLayout.setVerticalGroup(
            panelAlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlfabetoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbQual2)
                .addGroup(panelAlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlfabetoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panelAlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(letraE)
                            .addComponent(letraD)
                            .addComponent(letraC)
                            .addComponent(letraB)
                            .addComponent(letraA)
                            .addComponent(letraG)
                            .addComponent(letraF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(letraL)
                            .addComponent(letraK)
                            .addComponent(letraJ)
                            .addComponent(letraI)
                            .addComponent(letraH)
                            .addComponent(letraN)
                            .addComponent(letraM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(letraR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(letraP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(letraO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(letraQ))
                            .addComponent(letraS)
                            .addComponent(letraT)
                            .addComponent(letraU))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelAlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(letraW, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelAlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(letraX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(letraY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(letraZ, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(letraV))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlfabetoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );

        panelMenu.add(panelAlfabeto, "alfabeto");

        panelJogar.setBackground(new java.awt.Color(255, 255, 255));
        panelJogar.setPreferredSize(new java.awt.Dimension(777, 541));
        panelJogar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbChances.setFont(new java.awt.Font("Swis721 Blk BT", 0, 36)); // NOI18N
        lbChances.setForeground(new java.awt.Color(223, 84, 84));
        lbChances.setText("CHANCES:");
        panelJogar.add(lbChances, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, -1, -1));

        letra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/"+lSorteada1.getLetra()+".png")));
        letra2.setAlignmentX(0.5F);
        letra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra2ActionPerformed(evt);
            }
        });
        panelJogar.add(letra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        letra1.setBackground(new java.awt.Color(255, 255, 255));
        letra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/"+lSorteada.getLetra()+".png")));
        letra1.setAlignmentX(0.5F);
        letra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra1ActionPerformed(evt);
            }
        });
        panelJogar.add(letra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        letra3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/"+lSorteada2.getLetra()+".png")));
        letra3.setAlignmentX(0.5F);
        letra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra3ActionPerformed(evt);
            }
        });
        panelJogar.add(letra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        lbQual1.setFont(new java.awt.Font("Swis721 Blk BT", 0, 36)); // NOI18N
        lbQual1.setForeground(new java.awt.Color(98, 113, 111));
        lbQual1.setText("Qual é a letra:");
        panelJogar.add(lbQual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        lbAcer1.setFont(new java.awt.Font("Swis721 Blk BT", 0, 36)); // NOI18N
        lbAcer1.setForeground(new java.awt.Color(0, 153, 92));
        lbAcer1.setText("ACERTOS:");
        panelJogar.add(lbAcer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        lbAcertos.setFont(new java.awt.Font("Swis721 Blk BT", 0, 36)); // NOI18N
        lbAcertos.setForeground(new java.awt.Color(98, 113, 111));
        lbAcertos.setText(String.valueOf(score));
        panelJogar.add(lbAcertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 70, -1));

        lbChances1.setFont(new java.awt.Font("Swis721 Blk BT", 0, 36)); // NOI18N
        lbChances1.setForeground(new java.awt.Color(98, 113, 111));
        lbChances1.setText(String.valueOf(vida));
        panelJogar.add(lbChances1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, 100, -1));

        jButton2.setFont(new java.awt.Font("Swis721 Blk BT", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(98, 113, 111));
        jButton2.setText("< Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelJogar.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lbAcer4.setFont(new java.awt.Font("Swis721 Blk BT", 0, 36)); // NOI18N
        lbAcer4.setForeground(new java.awt.Color(204, 51, 0));
        lbAcer4.setText("X");
        lbAcer4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAcer4MouseClicked(evt);
            }
        });
        panelJogar.add(lbAcer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        panelMenu.add(panelJogar, "jogar");

        getContentPane().add(panelMenu, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void sortear() {
        List<Letra> alfabeto = letrasDAO.listarAlfabeto();
        int sorteado = rd.nextInt(alfabeto.size());
        lSorteada = letrasDAO.buscarId(sorteado);

        sorteado = rd.nextInt(alfabeto.size());
        lSorteada1 = letrasDAO.buscarId(sorteado);

        sorteado = rd.nextInt(alfabeto.size());
        lSorteada2 = letrasDAO.buscarId(sorteado);

        if (lSorteada == lSorteada1 || lSorteada == lSorteada2 || lSorteada1 == lSorteada2) {
            sortear();
        }
        if (lSorteada == null || lSorteada1 == null || lSorteada2 == null) {
            sortear();
        }
    }

    public Letra sortearCerta() {
        final int opSort = rd.nextInt(3);
        String letra = "letra" + opSort;
        Som.qual.play();
        final List<Letra> lts = new ArrayList<>();
        lts.add(lSorteada);
        lts.add(lSorteada1);
        lts.add(lSorteada2);
        try {
            new Thread() {
                public void run() {
                    try {
                        td.sleep(1500L);
                        lts.get(opSort).getSom().play();
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Inicial.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return lts.get(opSort);
    }

    private void acerteLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acerteLetraActionPerformed
        cl = (CardLayout) panelMenu.getLayout();
        cl.show(panelMenu, "jogar");
        vida = 3;
        this.certa = sortearCerta();

    }//GEN-LAST:event_acerteLetraActionPerformed

    private void alfabetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alfabetoActionPerformed
        Som.alfaCompleto.play();
        cl = (CardLayout) panelMenu.getLayout();
        cl.show(panelMenu, "alfabeto");
    }//GEN-LAST:event_alfabetoActionPerformed

    private void letraBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraBActionPerformed
        Som.b.play();
    }//GEN-LAST:event_letraBActionPerformed

    private void letraAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraAActionPerformed
        Som.a.play();
    }//GEN-LAST:event_letraAActionPerformed

    private void letraCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraCActionPerformed
        Som.c.play();
    }//GEN-LAST:event_letraCActionPerformed

    private void letraDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraDActionPerformed
        Som.d.play();
    }//GEN-LAST:event_letraDActionPerformed

    private void letraEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraEActionPerformed
        Som.e.play();
    }//GEN-LAST:event_letraEActionPerformed

    private void letraFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraFActionPerformed
        Som.f.play();
    }//GEN-LAST:event_letraFActionPerformed

    private void letraGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraGActionPerformed
        Som.g.play();
    }//GEN-LAST:event_letraGActionPerformed

    private void letraLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraLActionPerformed
        Som.l.play();
    }//GEN-LAST:event_letraLActionPerformed

    private void letraMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraMActionPerformed
        Som.m.play();
    }//GEN-LAST:event_letraMActionPerformed

    private void letraIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraIActionPerformed
        Som.i.play();
    }//GEN-LAST:event_letraIActionPerformed

    private void letraNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraNActionPerformed
        Som.n.play();
    }//GEN-LAST:event_letraNActionPerformed

    private void letraHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraHActionPerformed
        Som.h.play();
    }//GEN-LAST:event_letraHActionPerformed

    private void letraJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraJActionPerformed
        Som.j.play();
    }//GEN-LAST:event_letraJActionPerformed

    private void letraKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraKActionPerformed
        Som.k.play();
    }//GEN-LAST:event_letraKActionPerformed

    private void letraRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraRActionPerformed
        Som.r.play();
    }//GEN-LAST:event_letraRActionPerformed

    private void letraUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraUActionPerformed
        Som.u.play();
    }//GEN-LAST:event_letraUActionPerformed

    private void letraWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraWActionPerformed
        Som.w.play();
    }//GEN-LAST:event_letraWActionPerformed

    private void letraOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraOActionPerformed
        Som.o.play();
    }//GEN-LAST:event_letraOActionPerformed

    private void letraVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraVActionPerformed
        Som.v.play();
    }//GEN-LAST:event_letraVActionPerformed

    private void letraPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraPActionPerformed
        Som.p.play();
    }//GEN-LAST:event_letraPActionPerformed

    private void letraTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraTActionPerformed
        Som.t.play();
    }//GEN-LAST:event_letraTActionPerformed

    private void letraZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraZActionPerformed
        Som.z.play();
    }//GEN-LAST:event_letraZActionPerformed

    private void letraYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraYActionPerformed
        Som.y.play();
    }//GEN-LAST:event_letraYActionPerformed

    private void letraXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraXActionPerformed
        Som.x.play();
    }//GEN-LAST:event_letraXActionPerformed

    private void letraQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraQActionPerformed
        Som.q.play();
    }//GEN-LAST:event_letraQActionPerformed

    private void letraSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraSActionPerformed
        Som.s.play();
    }//GEN-LAST:event_letraSActionPerformed

    private void letra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra2ActionPerformed
        if (lSorteada1 == certa) {
            Som.acertou.play();
            this.score++;
            JOptionPane.showMessageDialog(null, "Voce Acertou!");
            panelJogar.removeAll();
            sortear();
            initComponents();
            cl = (CardLayout) panelMenu.getLayout();
            cl.show(panelMenu, "jogar");
            this.certa = sortearCerta();
        } else {
            Som.errou.play();
            vida--;
            JOptionPane.showMessageDialog(null, "Voce Errou!");
            if (vida <= 0) {
                Main.run(score);
                dispose();
            } else {
                panelJogar.removeAll();
                sortear();
                initComponents();
                cl = (CardLayout) panelMenu.getLayout();
                cl.show(panelMenu, "jogar");
                this.certa = sortearCerta();
            }
        }
    }//GEN-LAST:event_letra2ActionPerformed

    private void letra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra1ActionPerformed
        if (lSorteada == certa) {
            Som.acertou.play();
            this.score++;
            JOptionPane.showMessageDialog(null, "Voce Acertou!");
            panelJogar.removeAll();
            sortear();
            initComponents();
            cl = (CardLayout) panelMenu.getLayout();
            cl.show(panelMenu, "jogar");
            this.certa = sortearCerta();
        } else {
            Som.errou.play();
            vida--;
            JOptionPane.showMessageDialog(null, "Voce Errou!");
            if (vida <= 0) {
                Main.run(score);
                dispose();
            } else {
                panelJogar.removeAll();
                sortear();
                initComponents();
                cl = (CardLayout) panelMenu.getLayout();
                cl.show(panelMenu, "jogar");
                this.certa = sortearCerta();
            }
        }
    }//GEN-LAST:event_letra1ActionPerformed

    private void letra3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra3ActionPerformed
        if (lSorteada2 == certa) {
            Som.acertou.play();
            this.score++;
            JOptionPane.showMessageDialog(null, "Voce Acertou!");
            panelJogar.removeAll();
            sortear();
            initComponents();
            cl = (CardLayout) panelMenu.getLayout();
            cl.show(panelMenu, "jogar");
            this.certa = sortearCerta();
        } else {
            Som.errou.play();
            vida--;
            JOptionPane.showMessageDialog(null, "Voce Errou!");
            if (vida <= 0) {
                Main.run(score);
                dispose();
            } else {
                panelJogar.removeAll();
                sortear();
                initComponents();
                cl = (CardLayout) panelMenu.getLayout();
                cl.show(panelMenu, "jogar");
                this.certa = sortearCerta();
            }
        }
    }//GEN-LAST:event_letra3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cl.show(panelMenu, "principal");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lbAcer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAcer2MouseClicked
        Som.tshau.play();
        dispose();
    }//GEN-LAST:event_lbAcer2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cl.show(panelMenu, "principal");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lbAcer4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAcer4MouseClicked
        Som.tshau.play();
        dispose();
    }//GEN-LAST:event_lbAcer4MouseClicked

    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicial(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acerteLetra;
    private javax.swing.JButton alfabeto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbAcer1;
    private javax.swing.JLabel lbAcer2;
    private javax.swing.JLabel lbAcer3;
    private javax.swing.JLabel lbAcer4;
    private javax.swing.JLabel lbAcertos;
    private javax.swing.JLabel lbAcertos1;
    private javax.swing.JLabel lbChances;
    private javax.swing.JLabel lbChances1;
    private javax.swing.JLabel lbQual1;
    private javax.swing.JLabel lbQual2;
    private javax.swing.JToggleButton letra1;
    private javax.swing.JToggleButton letra2;
    private javax.swing.JToggleButton letra3;
    private javax.swing.JToggleButton letraA;
    private javax.swing.JToggleButton letraB;
    private javax.swing.JToggleButton letraC;
    private javax.swing.JToggleButton letraD;
    private javax.swing.JToggleButton letraE;
    private javax.swing.JToggleButton letraF;
    private javax.swing.JToggleButton letraG;
    private javax.swing.JToggleButton letraH;
    private javax.swing.JToggleButton letraI;
    private javax.swing.JToggleButton letraJ;
    private javax.swing.JToggleButton letraK;
    private javax.swing.JToggleButton letraL;
    private javax.swing.JToggleButton letraM;
    private javax.swing.JToggleButton letraN;
    private javax.swing.JToggleButton letraO;
    private javax.swing.JToggleButton letraP;
    private javax.swing.JToggleButton letraQ;
    private javax.swing.JToggleButton letraR;
    private javax.swing.JToggleButton letraS;
    private javax.swing.JToggleButton letraT;
    private javax.swing.JToggleButton letraU;
    private javax.swing.JToggleButton letraV;
    private javax.swing.JToggleButton letraW;
    private javax.swing.JToggleButton letraX;
    private javax.swing.JToggleButton letraY;
    private javax.swing.JToggleButton letraZ;
    private javax.swing.JPanel panelAlfabeto;
    private javax.swing.JPanel panelJogar;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
